server:
  port: 9081

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.114.221:3306/cloud_shop_user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: xdP.123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  mail:
    host: smtp.163.com
    port: 465
    username: 13679342025@163.com
    password: LZRUs38T6F3sSL7v
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.163.com
      mail.smtp.ssl.protocols: TLSv1.2
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
  jackson:
    serialization:
      write-dates-as-timestamps: false

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.cloudshop.user: INFO
    org.springframework.security: INFO
# JWT 配置
# JWT 配置
jwt:
  secret: "your-super-secret-jwt-key-here-make-it-long-and-random-at-least-256-bits"
  access-token-expiration: 3600000    # 访问令牌过期时间：1小时（毫秒）
  refresh-token-expiration: 2592000000 # 刷新令牌过期时间：30天（毫秒）