server:
  host: "0.0.0.0"
  port: 9082

database:
  host: "117.72.114.221"
  port: "3306"
  username: "root"
  password: "xdP.123456"
  database: "cloud_shop_product"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-super-secret-jwt-key-here-make-it-long-and-random-at-least-256-bits"

migrate:
  auto: false

nacos:
  enabled: true
  server_addr: "localhost:8848"
  username: "nacos"
  password: "nacos"
  namespace: "public"
  group: "DEFAULT_GROUP"
  data_id: "product-service-dev.yaml"

service:
  name: "product-service"
  register: true
  ip: "127.0.0.1"