spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&namespace=public&server-addr=localhost:8848&username=nacos&password=nacos
  cloud:
    nacos:
      # 统一配置 Nacos 连接与认证（Config 用于配置拉取，Discovery 用于注册）
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        namespace: public
      server-addr: ${spring.cloud.nacos.config.server-addr}
      username: nacos
      password: nacos
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
