spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&namespace=public
  cloud:
    nacos:
      # 配置中心基础连接参数（仅用于 spring.config.import 解析）
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        namespace: public
      # 服务注册发现
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        username: ${spring.cloud.nacos.config.username}
        password: ${spring.cloud.nacos.config.password}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: ${spring.cloud.nacos.config.group}

logging:
  level:
    com.alibaba.nacos.client.config.impl.ClientWorker: warn
