name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: [ "5432:5432" ]
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Java 服务 ----------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build User Service (Java)
        run: |
          cd services/user-service
          mvn clean install -DskipTests

      # ---------- Go 服务 ----------
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Product Service (Go)
        run: |
          cd services/product-service
          go build ./...

      # ---------- Python 服务 ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies (Payment Service)
        run: |
          cd services/payment-service
          pip install -r requirements.txt

      - name: Run Python linter
        run: |
          cd services/payment-service
          python -m py_compile app.py
